# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - todowebappduong

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://todoappduong.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b7e6b51295cf467c9411b284d907c892 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_97470cd1eefa44399ab32c36dcfde1f2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: todoappduong.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b7e6b51295cf467c9411b284d907c892 }}/todoapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'todowebappduong'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8159a14222d34e64a50614ccf1144409 }}
        images: 'todoappduong.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b7e6b51295cf467c9411b284d907c892 }}/todoapp:${{ github.sha }}'