# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - duongnxtodobackend

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://duongnxtodoacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4d44461c25184e6db06e0112d61eabba }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4e5642a2149147b992a7bdde8e89fca1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: duongnxtodoacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d44461c25184e6db06e0112d61eabba }}/todoapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'duongnxtodobackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b7c482d03527483d83f63cc039a675fe }}
        images: 'duongnxtodoacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d44461c25184e6db06e0112d61eabba }}/todoapp:${{ github.sha }}'