# This is a basic workflow to help you get started with Actions

name: CI/CD Asiggment (Thu 28 Jul 2022)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  unit_test:
    name: Testing (Unit, Integration)
    runs-on: ubuntu-latest
    
    env:
      PORT: 3001
      NODE_ENV: "development"
      DB_HOST: "localhost"
      DB_USERNAME: "todo"
      DB_NAME: "todo"
      DB_PASSWORD: "tester@123"
      DB_PORT: 5432
      HASH_KEY_PASSWORD: "HASH_KEY_PASSWORD"
      TOKEN_SECRET_KEY: "TOKEN_SECRET_KEY"
      TOKEN_EXPIRES_IN: "240m"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Run unit tests
        run: yarn test

  sonarqube:
    name: Static code analysis
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
    - name: Install dependencies
        run: yarn
      
    - name: Run coverage report
      run: yarn coverage
      
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
